accounts/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from accounts.views import signup


urlpatterns = [
    path("login/", LoginView.as_view(), name="login"),
    path("logout/", LogoutView.as_view(), name="logout"),
    path("signup/", signup, name="signup"),
]

projects/urls.py
from django.urls import path
from projects.views import (
    ProjectListView,
    ProjectDetailView,
    ProjectCreateView,
)


urlpatterns = [
    path("", ProjectListView.as_view(), name="list_projects"),
    path("<int:pk>/", ProjectDetailView.as_view(), name="show_project"),
    path("create/", ProjectCreateView.as_view(), name="create_project"),
]

tasks/urls.py
from django.urls import path
from tasks.views import TaskCreateView, TaskListView, TaskUpdateView

urlpatterns = [
    path("create/", TaskCreateView.as_view(), name="create_task"),
    path("mine/", TaskListView.as_view(), name="show_my_tasks"),
    path("<int:pk>/complete/", TaskUpdateView.as_view(), name="complete_task"),
]

tracker/urls.py
from django.views.generic.base import RedirectView
from django.contrib.auth import views as auth_views
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path("", RedirectView.as_view(url="/projects/"), name="home"),
    path("projects/", include("projects.urls")),
    path("admin/", admin.site.urls),
    path("accounts/", include("accounts.urls")),
    path("accounts/login/", auth_views.LoginView.as_view(), name="login"),
    path("tasks/", include("tasks.urls")),
]

accounts/models.py
# Create your models here.

projects/models.py
from django.db import models
from django.conf import settings


USER_MODEL = settings.AUTH_USER_MODEL


class Project(models.Model):
    name = models.CharField(max_length=200)
    description = models.TextField()
    members = models.ManyToManyField(USER_MODEL, related_name="projects")

    def __str__(self):
        return self.name

tasks/models.py
from django.db import models
from django.conf import settings

USER_MODEL = settings.AUTH_USER_MODEL


class Task(models.Model):
    name = models.CharField(max_length=200)
    start_date = models.DateTimeField()
    due_date = models.DateTimeField()
    is_completed = models.BooleanField(default=False)
    project = models.ForeignKey(
        "projects.Project",
        related_name="tasks",
        on_delete=models.CASCADE,
    )
    assignee = models.ForeignKey(
        USER_MODEL, related_name="tasks", on_delete=models.SET_NULL, null=True
    )

    def __str__(self):
        return self.name

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.contrib.auth import login


def signup(request):
    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            username = request.POST.get("username")
            password = request.POST.get("password")
            user = User.objects.create_user(
                username=username,
                password=password,
            )
            user.save()
            login(request, user)
            return redirect("home")
    else:
        form = UserCreationForm()
    context = {"form": form}
    return render(request, "registration/signup.html", context)

projects/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.shortcuts import redirect
from projects.models import Project
from django.views.generic import ListView, DetailView, CreateView
from django.contrib.auth.models import User

user = User.objects.create_user


class ProjectListView(LoginRequiredMixin, ListView):
    model = Project
    template_name = "projects/list.html"

    def get_queryset(self):
        return Project.objects.filter(members=self.request.user)


class ProjectDetailView(LoginRequiredMixin, DetailView):
    model = Project
    template_name = "projects/details.html"

    def get_queryset(self):
        return Project.objects.filter(members=self.request.user)


class ProjectCreateView(LoginRequiredMixin, CreateView):
    model = Project
    template_name = "projects/create.html"
    fields = ["name", "description", "members"]

    def get_success_url(self):
        return reverse_lazy("show_project", args=[self.object.id])

    def RedirectView(request):
        return redirect("list_projects", name="home")

tasks/views.py
from django.views.generic.edit import CreateView
from tasks.models import Task
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import ListView, UpdateView
from django.shortcuts import redirect
from django.urls import reverse_lazy


class TaskCreateView(LoginRequiredMixin, CreateView):
    model = Task
    template_name = "tasks/task_create.html"
    fields = ["name", "start_date", "due_date", "project", "assignee"]

    def form_valid(self, form):
        item = form.save(commit=False)
        item.owner = self.request.user
        item.save()
        return redirect("show_my_tasks")


class TaskListView(LoginRequiredMixin, ListView):
    model = Task
    template_name = "tasks/list.html"

    def get_queryset(self):
        return Task.objects.filter(assignee=self.request.user)


class TaskUpdateView(UpdateView):
    model = Task
    template_name = "tasks/edit.html"
    fields = ["is_completed"]
    success_url = reverse_lazy("show_my_tasks")

projects/templates/projects/create.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Create</title>
</head>
<body>
    <header>
        <nav>
            <ul>
                <li>
                    <a href="{% url "show_my_tasks" %}">My Tasks</a>
                </li>
                <li>
                    <a href="{% url "list_projects" %}">My Projects</a>
                </li>
                <li>
                    <a href="{% url "logout" %}">Logout</a>
                </li>
            </ul>
        </nav>
    </header>
    <main>
        <div>
            <h1>Create a new project</h1>
            <form method="POST">
                {% csrf_token %}
                {{ form.as_p }}
                <div class="control">
                    <button class="button">Create</button>
                </div>
            </form>
        </div>
    </main>
</body>
</html>

projects/templates/projects/details.html
{% load markdownify %}

<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Details</title>
</head>
<body>
  <header>
      <nav>
        <ul>
            <li>
                <a href="{% url "show_my_tasks" %}">My Tasks</a>
            </li>
            <li>
                <a href="{% url "list_projects" %}">My Projects</a>
            </li>
            <li>
                <a href="{% url "logout" %}">Logout</a>
            </li>
        </ul>
      </nav>
  </header>
  <main>
    <div>
        <h1>{{project.name}}</h1>
        <p>{{ project.description|markdownify }}</p>
        <h2>Tasks</h2>
    </div>
        <ul>
          <li>
            <a href="{% url "create_task" %}">Create a new task</a>
          </li>
        </ul>
    <table>
      <thead>
        <tr>
          <th>Name</th>
          <th>Assignee</th>
          <th>Start date</th>
          <th>Due date</th>
          <th>Is completed</th>
        </tr>
      </thead>
        <tbody>
          <tr>
            {% for item in task_list %}
            {% if task_list %}
          <td>{{item.name}}</td>
          <td>{{item.assignee}}</td>
          <td>{{item.start_date}}</td>
          <td>{{item.due_date}}</td>
          <td>{{item.is_completed}}</td>
            {% endif %}
            {% endfor %}
          </tr>
        </tbody>
      </thead
    </table>
      {% if not tasks_list %}
        <p>This project has no tasks</p>
      {% endif %}
  </main>
</body>
</html>

projects/templates/projects/list.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Projects</title>
</head>
<body>
    <header>
        <nav>
            <ul>
                <li>
                    <a href="{% url "show_my_tasks" %}">My Tasks</a>
                </li>
                <li>
                    <a href="{% url "list_projects" %}">My Projects</a>
                </li>
                <li>
                    <a href="{% url "logout" %}">Logout</a>
                </li>
            </ul>
        </nav>
    </header>
        <main>
            <div>
                <h1> My Projects </h1>
            </div>
                <ul>
                    <li>
                        <a href="{% url "create_project" %}">Create a Project</a>
                    </li>
                </ul>
                <table>
                    <thead>
                        <tr>
                            {% if project_list%}
                                <th>Name</th>
                                <th>Number of tasks</th>
                            {% endif %}
                                    </tr>
                    </thead>
                        <tbody>
                            {% for item in project_list %}
                                <tr>
                                <td>
                                <a href="{% url "show_project" item.pk %}">{{ item.name }}</a>
                                </td>
                                <td> {{ item.tasks.count }}</td>
                                </tr>
                            {% endfor %}
                                </tbody>
                            </table>
                            {% if not project_list%}
                                <p> You are not assigned to any projects</p>
                            {%endif%}
        </main>
</body>

</html>

tasks/templates/tasks/list.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Tasks</title>
</head>

<body>
    <header>
        <nav>
            <ul>
                <li>
                    <a href="{% url "show_my_tasks" %}">My Tasks</a>
                </li>
                <li>
                    <a href="{% url "list_projects" %}">My Projects</a>
                </li>
                <li>
                    <a href="{% url "logout" %}">Logout</a>
                </li>
            </ul>
        </nav>
    </header>
    <main>
        <div>
            <h1> My Tasks </h1>
                <ul>
                    <li>
                        <a href="{% url "create_task" %}">Create a new Task</a>
                    </li>
                </ul>
                    <table>
                        <thead>
                            <tr>
                            {% if task_list %}
                            <th>Name</th>
                            <th>Start date</th>
                            <th>End date</th>
                            <th>Is completed</th>
                            {%endif%}
                            </tr>
                        </thead>
                        <tbody>
                            {% for item in task_list%}
                            <tr>
                            <td>{{item.name}}</td>
                            <td>{{item.start_date|date:"m-d-Y" }}</td>
                            <td>{{item.due_date|date:"m-d-Y" }}</td>
                            <td>{{item.is_completed}}</td>
                            </tr>
                        {% endfor%}
                        </tbody>
                    </table>
                    {% if not task_list %}
                    <p> You have no tasks </p>
                    {% endif %}
        </div>
    </main>
</body>
</html>

tasks/templates/tasks/task_create.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Create a Task</title>
</head>

<body>
    <header>
        <nav>
            <ul>
                <li>
                    <a href="{% url "show_my_tasks" %}">My Tasks</a>
                </li>
                <li>
                    <a href="{% url "list_projects" %}">My Projects</a>
                </li>
                <li>
                    <a href="{% url "logout" %}">Logout</a>
                </li>
            </ul>
        </nav>
    </header>
    <main>
        <div>
            <h1> Create a new Task </h1>
            <form method="POST">
                {% csrf_token %}
                {{ form.as_p }}
                <div class="control">
                    <button class="button">Create</button>
                </div>
            </form>
        </div>
    </main>
</body>
</html>